### PR TITLE
Move to uplc>=1.0.0

### PR DESCRIPTION
**Pull request by SCMusson**
TODO:

- [x] UPLC version dependency on pycardano=0.10.* needs fixing to match with Opshins pycardano=0.11.*
- [x] pluthon version dependency on UPLC 0.6.* needs updating to UPLC=1.0.*  (I think there is an existing pull request)
- [x] UPLC 1.0.6 PyPi published
- [x] Run `poetry lock`

### CODE REVIEW

**Comment by SCMusson** [comment]
Everything looks good from my end

**Comment by nielstron** [comment]
Yes this looks also good to me. Please bear with me until the next milestone payout of the [Catalyst Fund](https://milestones.projectcatalyst.io/projects/1100219/milestones/2) has been completed so that I will be able to transfer the reward (same for #386 )

**Comment by nielstron** [comment]
@SCMusson can you please post the payment address for claiming the bug bounty of this PR? :)

**Comment by SCMusson** [comment]
addr1qxsprna8457kszz9kzffg7y886nme4llpnprr6s3pzgeg7d93vtsr3yl4f3553sxfx7wzx58cx5pnhekvtlgqf55lw9s69kv6a

**Comment by nielstron** [comment]
Payment initiated 🎉
f337271142c0364096484dd2409205b4755d8f0d4b60a6a72db0d6f565972c3e

**Pull request merged**
